package com.weibuddy.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.weibuddy.Category;
import com.weibuddy.Content;
import com.weibuddy.Folder;

import com.weibuddy.dao.CategoryDao;
import com.weibuddy.dao.ContentDao;
import com.weibuddy.dao.FolderDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig categoryDaoConfig;
    private final DaoConfig contentDaoConfig;
    private final DaoConfig folderDaoConfig;

    private final CategoryDao categoryDao;
    private final ContentDao contentDao;
    private final FolderDao folderDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        categoryDaoConfig = daoConfigMap.get(CategoryDao.class).clone();
        categoryDaoConfig.initIdentityScope(type);

        contentDaoConfig = daoConfigMap.get(ContentDao.class).clone();
        contentDaoConfig.initIdentityScope(type);

        folderDaoConfig = daoConfigMap.get(FolderDao.class).clone();
        folderDaoConfig.initIdentityScope(type);

        categoryDao = new CategoryDao(categoryDaoConfig, this);
        contentDao = new ContentDao(contentDaoConfig, this);
        folderDao = new FolderDao(folderDaoConfig, this);

        registerDao(Category.class, categoryDao);
        registerDao(Content.class, contentDao);
        registerDao(Folder.class, folderDao);
    }
    
    public void clear() {
        categoryDaoConfig.clearIdentityScope();
        contentDaoConfig.clearIdentityScope();
        folderDaoConfig.clearIdentityScope();
    }

    public CategoryDao getCategoryDao() {
        return categoryDao;
    }

    public ContentDao getContentDao() {
        return contentDao;
    }

    public FolderDao getFolderDao() {
        return folderDao;
    }

}
